**Group 6** 
1. Carmen Mendoza
2. Joaquín Pérez
3. Lizbeth Minaya
4. Valeria Albarracín

# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [3]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [17]:
#Show np1
np1 = np.arange( 200, 750)
np1

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38

In [18]:
# Create a boolean that when a value of 'np1' is divided by 2 and the remainder is 0,it returns True
#This boolean works as a kind of filter
number=np1%2==0
#Now, every time the filer get a true result, this will be replace with 100
np1[number] =100
np1

array([200, 201, 202, 100, 204, 205, 206, 207, 208, 100, 210, 211, 212,
       213, 214, 100, 216, 217, 218, 219, 220, 100, 222, 223, 224, 225,
       226, 100, 228, 229, 230, 231, 232, 100, 234, 235, 236, 237, 238,
       100, 240, 241, 242, 243, 244, 100, 246, 247, 248, 249, 250, 100,
       252, 253, 254, 255, 256, 100, 258, 259, 260, 261, 262, 100, 264,
       265, 266, 267, 268, 100, 270, 271, 272, 273, 274, 100, 276, 277,
       278, 279, 280, 100, 282, 283, 284, 285, 286, 100, 288, 289, 290,
       291, 292, 100, 294, 295, 296, 297, 298, 100, 300, 301, 302, 303,
       304, 100, 306, 307, 308, 309, 310, 100, 312, 313, 314, 315, 316,
       100, 318, 319, 320, 321, 322, 100, 324, 325, 326, 327, 328, 100,
       330, 331, 332, 333, 334, 100, 336, 337, 338, 339, 340, 100, 342,
       343, 344, 345, 346, 100, 348, 349, 350, 351, 352, 100, 354, 355,
       356, 357, 358, 100, 360, 361, 362, 363, 364, 100, 366, 367, 368,
       369, 370, 100, 372, 373, 374, 375, 376, 100, 378, 379, 38

2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method

In [6]:
#Create an array with the values from 0 to 8.
a=np.arange(9)
print(a)
#To create a 3x3 matrix, we reshape 'a' and put the dimensions
b=np.reshape(,(3,3))
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [7]:
#Create an array Z with values from 1 to 10
Z = np.arange(1,11)
#Generate a new array 'R' by concatenating intervals of 'Z'
#Each interval contains four elements
R = np.concatenate(([Z[0:4]], [Z[1:5]], [Z[2:6]], [Z[3:7]], [Z[4:8]], [Z[5:9]], [Z[6:10]]), axis=0)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [22]:
#First, I created and array with random values indicating it is 3x3x3, using np.random.random
array = np.random.random((3,3,3))
#Next I printed the output
print(array)



[[[0.53782742 0.59577428 0.21330486]
  [0.37023132 0.38115797 0.78936462]
  [0.67138119 0.73383594 0.13626683]]

 [[0.47537952 0.9263402  0.54434102]
  [0.80408486 0.41346292 0.92569562]
  [0.12252464 0.10250705 0.35699555]]

 [[0.3973671  0.70295335 0.20824051]
  [0.5001293  0.49553133 0.36636986]
  [0.57103084 0.95094085 0.53773297]]]


5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

np.nan == np.nan

In [23]:
np.nan == np.nan
#The reason the expression np.nan == np.nan is False may be in that NaN are just substitutes or "place-holders" for missing numerical values. 
#Nonetheless, that does not imply that the original numerical values of different NaN are the same: NaN is just working as a constant. 
#Hence, the expression np.nan == np.nan is False as far as the original numerical values are unknown, 
# so it is not possible to assert they are equivalent.


False

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [19]:
#First I calculated the mean for np2 using np.mean and saved it
mean = np.mean(np2)
#Then I rounded the mean to two digits
mean = str(round(mean, 2))

#Second I calculated the standard deviation for np2 using np.mean and saved it
var = np.var(np2)
#Then I rounded the standard deviation to two digits
var = str(round(var, 2))

#Finally I printed the output with f-string
print(f"The mean of np2 is {mean}, and the standard deviation is {var} ")


The mean of np2 is 49.91, and the standard deviation is 18.18 


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [14]:
import pandas as pd

In [15]:
pip install savReaderWriter

Note: you may need to restart the kernel to use updated packages.


In [16]:
pip install pyreadstat

Note: you may need to restart the kernel to use updated packages.


In [17]:
#We install the requested library
import savReaderWriter as sav

In [20]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [21]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [26]:
#ACT1
# We check if CASEID uniquely identifies each observation with the "is_unique" function

( rec1[ 'CASEID' ] ).is_unique

True

In [27]:
#ACT2
# Make the CASEISD column the index of its data set with "set_index"

rec1.set_index('CASEID')


ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

In [29]:
#ACT3
# Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.
rec1.query('V012>15 & V012<30 & V025=="Urbano"')

ID1             HHID              CASEID    V001   V002  V003  \
4      2019.0        000104801        000104801  2     1.0   48.0   2.0   
8      2019.0        000116701        000116701  1     1.0  167.0   1.0   
9      2019.0        000119101        000119101  1     1.0  191.0   1.0   
12     2019.0        000203001        000203001  2     2.0   30.0   2.0   
14     2019.0        000204001        000204001  3     2.0   40.0   3.0   
...       ...              ...                 ...     ...    ...   ...   
38162  2019.0        324202401        324202401  2  3242.0   24.0   2.0   
38163  2019.0        324202501        324202501  3  3242.0   25.0   3.0   
38164  2019.0        324203901        324203901  1  3242.0   39.0   1.0   
38165  2019.0        324204501        324204501  2  3242.0   45.0   2.0   
38170  2019.0        324206901        324206901  3  3242.0   69.0   3.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
8         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
9         1.0  2019.0  1434.0   9.0  ...       No       No       No  010101   
12        2.0  2019.0  1432.0   5.0  ...       No       No       No  010101   
14        2.0  2019.0  1432.0   9.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38162  3242.0  2019.0  1436.0   2.0  ...       No       No       No  250302   
38163  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38164  3242.0  2019.0  1436.0   8.0  ...       No       No       No  250302   
38165  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38170  3242.0  2019.0  1436.0  10.0  ...       No       No       No  250302   

        V022      V005          V190      V191  \
4        3.0  154803.0        Pobrer -0.256431   
8        3.0  154803.0      Más rico  1.672440   
9        3.0  154803.0        Pobrer  0.234148   
12       2.0   65298.0        Pobrer -0.196449   
14       2.0   65298.0         Medio  0.560448   
...      ...       ...           ...       ...   
38162  248.0  203603.0        Pobrer -0.463931   
38163  248.0  567613.0        Pobrer -0.576118   
38164  248.0  567613.0  El más pobre -0.940013   
38165  248.0  203603.0  El más pobre -0.656011   
38170  248.0  567613.0        Pobrer -0.574662   

                          mujeres12a49  NCONGLOME  
4      Mujeres de 15 a 49 años de edad     7065.0  
8      Mujeres de 15 a 49 años de edad     7065.0  
9      Mujeres de 15 a 49 años de edad     7065.0  
12     Mujeres de 15 a 49 años de edad     7068.0  
14     Mujeres de 15 a 49 años de edad     7068.0  
...                                ...        ...  
38162  Mujeres de 15 a 49 años de edad    45556.0  
38163  Mujeres de 15 a 49 años de edad    45556.0  
38164  Mujeres de 15 a 49 años de edad    45556.0  
38165  Mujeres de 15 a 49 años de edad    45556.0  
38170  Mujeres de 15 a 49 años de edad    45556.0  

[10606 rows x 105 columns]

In [31]:
#ACT4
# Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.
rec1['month']= pd.to_datetime(rec1['V009'], format='%m').dt.month_name().str.slice(stop=3)
rec1

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_5  QD333_6  UBIGEO   V022  \
0         1.0  2019.0  1434.0   4.0  ...       No       No  010101    3.0   
1         1.0  2019.0  1434.0   1.0  ...       No       No  010101    3.0   
2         1.0  2019.0  1434.0   6.0  ...       No       No  010101    3.0   
3         1.0  2019.0  1434.0   3.0  ...       No       No  010101    3.0   
4         1.0  2019.0  1434.0   5.0  ...       No       No  010101    3.0   
...       ...     ...     ...   ...  ...      ...      ...     ...    ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No  250401  249.0   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No  250401  249.0   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No  250401  249.0   

           V005          V190      V191  \
0      154803.0          Rico  1.234450   
1      154803.0          Rico  1.234450   
2      154803.0          Rico  1.295611   
3      154803.0          Rico  1.295611   
4      154803.0        Pobrer -0.256431   
...         ...           ...       ...   
38330  244995.0  El más pobre -1.750187   
38331  244995.0  El más pobre -1.676861   
38332  459792.0  El más pobre -1.585333   
38333  459792.0  El más pobre -1.650159   
38334  244995.0  El más pobre -1.644720   

                                        mujeres12a49 NCONGLOME  month  
0                    Mujeres de 15 a 49 años de edad    7065.0    Apr  
1      Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0    Jan  
2                    Mujeres de 15 a 49 años de edad    7065.0    Jun  
3                    Mujeres de 15 a 49 años de edad    7065.0    Mar  
4                    Mujeres de 15 a 49 años de edad    7065.0    May  
...                                              ...       ...    ...  
38330                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38331                Mujeres de 15 a 49 años de edad   15783.0    Jun  
38332                Mujeres de 15 a 49 años de edad   15783.0    Jul  
38333                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38334                Mujeres de 15 a 49 años de edad   15783.0    Oct  

[38335 rows x 106 columns]