# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [1]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>


In [2]:
# Filter the even numbers that returns a boolean
np1[np1%2 == 0] = 100

print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [3]:
# Create a 1D array with values from 0 to 8
array = np.arange(9)

# Convert the 1D array into a 3x3 matrix using the n.p reshape method
matrix = array.reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [4]:
# Create an array z with values from 1 to 10
z = np.arange(1,11)

# Generate a new array r concatenating z's intervals 
z = np.concatenate(([z[0:4]], [z[1:5]], [z[2:6]], [z[3:7]], [z[4:8]], [z[5:9]], [z[6:10]]), axis = 0)
z

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [5]:
# Create an 3x3x3 array with random values indicating it is 3x3x3
array_3 = np.random.random((3,3,3))

print(array_3)

[[[0.74782768 0.84991665 0.57325237]
  [0.91241726 0.89340346 0.40465349]
  [0.98218268 0.09751411 0.35273447]]

 [[0.39901903 0.06709536 0.81005433]
  [0.32435436 0.25462515 0.61742201]
  [0.17648625 0.28766609 0.3261455 ]]

 [[0.5301929  0.80000972 0.93954206]
  [0.32784979 0.14315508 0.53548284]
  [0.77671465 0.10856533 0.9823339 ]]]


5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

In [6]:
np.nan == np.nan

False

`np.nan` are not numbers, but are undefined values that are substitutes for the empty spaces of an array, in this case, since we are working with numpys. So, it does not make much mathematical sense to compare two undefined values.

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [7]:
np2 = np.random.normal(50 , 4, 300)

# Get the mean for np2 and round it
mean = np.mean(np2)
mean = str(round(mean, 2))

# Get the standard deviation for np2 and round it
var = np.var(np2)
var = str(round(var, 2))

#Finally I printed the output with f-string
print(f'The mean of np2 is {mean}, and the standard deviation is {var}')


The mean of np2 is 49.54, and the standard deviation is 15.49


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [10]:
import pandas as pd
import savReaderWriter as sav

In [14]:
# read REC0111 data
rec1 = pd.read_spss( fr"/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [15]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**

In [16]:
# Check if CASEID uniquely identifies each observation
rec1['CASEID'].is_unique

True

2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 

In [18]:
# Set  CASEISD column as the index
rec1.set_index('CASEID')

ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.

In [28]:
# Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.
rec_1 = rec1.query('V012>15 & V012<30 & V025 == "Urbano"')
rec_1

ID1             HHID              CASEID    V001   V002  V003  \
4      2019.0        000104801        000104801  2     1.0   48.0   2.0   
8      2019.0        000116701        000116701  1     1.0  167.0   1.0   
9      2019.0        000119101        000119101  1     1.0  191.0   1.0   
12     2019.0        000203001        000203001  2     2.0   30.0   2.0   
14     2019.0        000204001        000204001  3     2.0   40.0   3.0   
...       ...              ...                 ...     ...    ...   ...   
38162  2019.0        324202401        324202401  2  3242.0   24.0   2.0   
38163  2019.0        324202501        324202501  3  3242.0   25.0   3.0   
38164  2019.0        324203901        324203901  1  3242.0   39.0   1.0   
38165  2019.0        324204501        324204501  2  3242.0   45.0   2.0   
38170  2019.0        324206901        324206901  3  3242.0   69.0   3.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
8         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
9         1.0  2019.0  1434.0   9.0  ...       No       No       No  010101   
12        2.0  2019.0  1432.0   5.0  ...       No       No       No  010101   
14        2.0  2019.0  1432.0   9.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38162  3242.0  2019.0  1436.0   2.0  ...       No       No       No  250302   
38163  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38164  3242.0  2019.0  1436.0   8.0  ...       No       No       No  250302   
38165  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38170  3242.0  2019.0  1436.0  10.0  ...       No       No       No  250302   

        V022      V005          V190      V191  \
4        3.0  154803.0        Pobrer -0.256431   
8        3.0  154803.0      Más rico  1.672440   
9        3.0  154803.0        Pobrer  0.234148   
12       2.0   65298.0        Pobrer -0.196449   
14       2.0   65298.0         Medio  0.560448   
...      ...       ...           ...       ...   
38162  248.0  203603.0        Pobrer -0.463931   
38163  248.0  567613.0        Pobrer -0.576118   
38164  248.0  567613.0  El más pobre -0.940013   
38165  248.0  203603.0  El más pobre -0.656011   
38170  248.0  567613.0        Pobrer -0.574662   

                          mujeres12a49  NCONGLOME  
4      Mujeres de 15 a 49 años de edad     7065.0  
8      Mujeres de 15 a 49 años de edad     7065.0  
9      Mujeres de 15 a 49 años de edad     7065.0  
12     Mujeres de 15 a 49 años de edad     7068.0  
14     Mujeres de 15 a 49 años de edad     7068.0  
...                                ...        ...  
38162  Mujeres de 15 a 49 años de edad    45556.0  
38163  Mujeres de 15 a 49 años de edad    45556.0  
38164  Mujeres de 15 a 49 años de edad    45556.0  
38165  Mujeres de 15 a 49 años de edad    45556.0  
38170  Mujeres de 15 a 49 años de edad    45556.0  

[10606 rows x 105 columns]

4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [31]:
# Generate a new column with the first three letters of the month of born
rec_2 = rec1['month']= pd.to_datetime(rec1['V009'], format='%m').dt.month_name().str.slice(stop=3)
rec_2

0        Apr
1        Jan
2        Jun
3        Mar
4        May
        ... 
38330    Dec
38331    Jun
38332    Jul
38333    Dec
38334    Oct
Name: V009, Length: 38335, dtype: object

In [32]:
rec1

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_5  QD333_6  UBIGEO   V022  \
0         1.0  2019.0  1434.0   4.0  ...       No       No  010101    3.0   
1         1.0  2019.0  1434.0   1.0  ...       No       No  010101    3.0   
2         1.0  2019.0  1434.0   6.0  ...       No       No  010101    3.0   
3         1.0  2019.0  1434.0   3.0  ...       No       No  010101    3.0   
4         1.0  2019.0  1434.0   5.0  ...       No       No  010101    3.0   
...       ...     ...     ...   ...  ...      ...      ...     ...    ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No  250401  249.0   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No  250401  249.0   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No  250401  249.0   

           V005          V190      V191  \
0      154803.0          Rico  1.234450   
1      154803.0          Rico  1.234450   
2      154803.0          Rico  1.295611   
3      154803.0          Rico  1.295611   
4      154803.0        Pobrer -0.256431   
...         ...           ...       ...   
38330  244995.0  El más pobre -1.750187   
38331  244995.0  El más pobre -1.676861   
38332  459792.0  El más pobre -1.585333   
38333  459792.0  El más pobre -1.650159   
38334  244995.0  El más pobre -1.644720   

                                        mujeres12a49 NCONGLOME  month  
0                    Mujeres de 15 a 49 años de edad    7065.0    Apr  
1      Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0    Jan  
2                    Mujeres de 15 a 49 años de edad    7065.0    Jun  
3                    Mujeres de 15 a 49 años de edad    7065.0    Mar  
4                    Mujeres de 15 a 49 años de edad    7065.0    May  
...                                              ...       ...    ...  
38330                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38331                Mujeres de 15 a 49 años de edad   15783.0    Jun  
38332                Mujeres de 15 a 49 años de edad   15783.0    Jul  
38333                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38334                Mujeres de 15 a 49 años de edad   15783.0    Oct  

[38335 rows x 106 columns]