# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [72]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [91]:
#We create a filter even_numbers, that returns a boolean, when np1 is even, it returns True
even_numbers = np1%2==0

#We index with the filter and replace the values that achieve the condition with 100
np1[even_numbers] = 100

In [92]:
np1

array([[100],
       [201],
       [100],
       [203],
       [100],
       [205],
       [100],
       [207],
       [100],
       [209],
       [100],
       [211],
       [100],
       [213],
       [100],
       [215],
       [100],
       [217],
       [100],
       [219],
       [100],
       [221],
       [100],
       [223],
       [100],
       [225],
       [100],
       [227],
       [100],
       [229],
       [100],
       [231],
       [100],
       [233],
       [100],
       [235],
       [100],
       [237],
       [100],
       [239],
       [100],
       [241],
       [100],
       [243],
       [100],
       [245],
       [100],
       [247],
       [100],
       [249],
       [100],
       [251],
       [100],
       [253],
       [100],
       [255],
       [100],
       [257],
       [100],
       [259],
       [100],
       [261],
       [100],
       [263],
       [100],
       [265],
       [100],
       [267],
       [100],
       [269],
       [100],
      

2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method.

In [61]:
#We create an array with the values from 0 to 8. 
#Note that the range is exclusive so it is (0,9) in order to include the 8
matrix = np.arange(0,9)

#We reshape it so it becomes a 3x3 matix
matrix=np.reshape(matrix,(3,3))   
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array Z = [1,2,3,4,5,6,7,8,9,10], generate an array R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]?.Hint: Use np.arange and np.concatenate

In [62]:
#We create an array Z with values from 1 to 10
Z = np.arange(1,11)

#We concatenate fractions of Z by indexing Z as suggested by the exercise
R = np.concatenate(([Z[0:4]], [Z[1:5]], [Z[2:6]], [Z[3:7]], [Z[4:8]], [Z[5:9]], [Z[6:10]]), axis=0)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [14]:
#We generate three vectors with the command np.random.random, which
#give you random values. 
np_random = np.random.random((3,3))
np_random


array([[0.39725534, 0.98045478, 0.01737665],
       [0.4414128 , 0.75850407, 0.22890397],
       [0.86046045, 0.57519278, 0.78884178]])

5. Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow.

In [15]:
#nan is not a number and is a commom missing data representation. Nan cannot be equal to itself because nnan is the result of a failure
#The result of one failure cannot be equal to the result of any other failure
#and unknown values cannot be equal to each other.

np.nan==np.nan

False

6. Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

In [23]:
#First, we get the mean and variance with the command np_mean and np_var, rescpectively.
#After that, we use f-string to show the value of the variables as a string.

type(np2)
#f-string 
#np.meam
np_mean= np.mean(np2) 
np_var=np.var(np2)
f"La desviación estándar de np2 es {np_mean}. Y su media es {np_var}"

'La desviación estándar de np2 es 50.13089160509619. Y su media es 16.470711192615507'

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [21]:
# read REC0111 data
!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss(r"C:\Users\brisa\OneDrive\Documentos\QLAB_Summer_Python\assignments\assignment_3/RE516171.sav" )

# Get labels from sav file
with sav.SavHeaderReader(r"C:\Users\brisa\OneDrive\Documentos\QLAB_Summer_Python\assignments\assignment_3/RE516171.sav",
                         ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [22]:
dict_varlabels

{'ID1': 'Año',
 'CASEID': 'Identificación Cuestionario Individual',
 'V501': 'Estado civil actual',
 'V502': 'Actualmente, antes o nunca sacada',
 'V503': 'Usted ha estado casada o conviviendo solo una vez, más de una vez',
 'V504': 'Su esposo/compañer vive en el hogar o vive en otro lugar',
 'V505': 'Número de otras esposas',
 'V506': 'Número de rango de la esposa',
 'V507': 'Mes - Primer matrimonio',
 'V508': 'Año - Primer matrimonio',
 'V509': 'Fecha del primer matrimonio (CMC)',
 'V510': 'Integridad de la información para la fecha de inicio del primer matrimonio o unión',
 'V511': 'Edad al primer matrimonio',
 'V512': 'Años desde el primer matrimonio',
 'V513': 'Duración del matrimonio (agrupado)',
 'V525': 'Edad en la primera relación sexual',
 'V527': 'Tiempo transcurrido desde la última relación sexual',
 'V528': 'Tiempo transcurrido desde la última relación sexual en días',
 'V529': 'Tiempo transcurrido desde la última relación sexual (imputada)',
 'V530': 'Indicador para v529'

In [32]:
type(rec1)

pandas.core.frame.DataFrame

### 1

In [42]:
# "rec1" to call our df, "'CASEID'" to specify we want that variable to be evaluated by the function "is_unique"
( rec1[ 'CASEID'] ).is_unique

True

### 2

In [38]:
# "rec1" to call our df, "set_index" to call the method
rec1.set_index('CASEID') # "'CASEID'" to specify we want our index to be named after that variable

ID1             V501                  V502  \
CASEID                                                              
      000100201  2  2019.0           Casado    Actualmente casada   
      000102801  2  2019.0  Viviendo juntos    Actualmente casada   
      000102801  6  2019.0  No viven juntos  Anteriormente casada   
      000104801  2  2019.0  Viviendo juntos    Actualmente casada   
      000113601  2  2019.0  Viviendo juntos    Actualmente casada   
...                    ...              ...                   ...   
      325406201  2  2019.0  Viviendo juntos    Actualmente casada   
      325406301  2  2019.0  Viviendo juntos    Actualmente casada   
      325407001  2  2019.0  Viviendo juntos    Actualmente casada   
      325407201  2  2019.0  Viviendo juntos    Actualmente casada   
      325407401  2  2019.0  Viviendo juntos    Actualmente casada   

                              V503           V504 V505 V506  V507    V508  \
CASEID                                                                      
      000100201  2         Una vez  Vive con ella  NaN  NaN   1.0  2008.0   
      000102801  2         Una vez  Vive con ella  NaN  NaN  12.0  2011.0   
      000102801  6         Una vez            NaN  NaN  NaN   8.0  1984.0   
      000104801  2         Una vez  Vive con ella  NaN  NaN  12.0  2009.0   
      000113601  2  Mas de una vez  Vive con ella  NaN  NaN  12.0  2005.0   
...                            ...            ...  ...  ...   ...     ...   
      325406201  2  Mas de una vez  Vive con ella  NaN  NaN  12.0  1985.0   
      325406301  2         Una vez  Vive con ella  NaN  NaN  12.0  2002.0   
      325407001  2         Una vez  Vive con ella  NaN  NaN  11.0  1986.0   
      325407201  2         Una vez  Vive con ella  NaN  NaN   5.0  2008.0   
      325407401  2         Una vez  Vive con ella  NaN  NaN   6.0  2013.0   

                      V509  ...                            V743C  \
CASEID                      ...                                    
      000100201  2  1297.0  ...                     Entrevistada   
      000102801  2  1344.0  ...  Entrevistada y esposo/compañero   
      000102801  6  1016.0  ...                              NaN   
      000104801  2  1320.0  ...                     Entrevistada   
      000113601  2  1272.0  ...                     Entrevistada   
...                    ...  ...                              ...   
      325406201  2  1032.0  ...  Entrevistada y esposo/compañero   
      325406301  2  1236.0  ...                     Entrevistada   
      325407001  2  1043.0  ...                 Esposo/compañero   
      325407201  2  1301.0  ...                 Esposo/compañero   
      325407401  2  1362.0  ...                 Esposo/compañero   

                                              V743D  \
CASEID                                                
      000100201  2  Entrevistada y esposo/compañero   
      000102801  2                     Entrevistada   
      000102801  6                              NaN   
      000104801  2                     Entrevistada   
      000113601  2                     Entrevistada   
...                                             ...   
      325406201  2  Entrevistada y esposo/compañero   
      325406301  2                     Entrevistada   
      325407001  2                 Esposo/compañero   
      325407201  2                     Entrevistada   
      325407401  2                 Esposo/compañero   

                                              V743E  \
CASEID                                                
      000100201  2                     Entrevistada   
      000102801  2                     Entrevistada   
      000102801  6                              NaN   
      000104801  2                     Entrevistada   
      000113601  2  Entrevistada y esposo/compañero   
...                                             ...   
      325406201  2  Entrevistada y esposo/compañero   
      325406301  2         