# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [1]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [22]:
#First, I created and array with random values indicating it is 3x3x3, using np.random.random
array = np.random.random((3,3,3))
#Next I printed the output
print(array)



[[[0.53782742 0.59577428 0.21330486]
  [0.37023132 0.38115797 0.78936462]
  [0.67138119 0.73383594 0.13626683]]

 [[0.47537952 0.9263402  0.54434102]
  [0.80408486 0.41346292 0.92569562]
  [0.12252464 0.10250705 0.35699555]]

 [[0.3973671  0.70295335 0.20824051]
  [0.5001293  0.49553133 0.36636986]
  [0.57103084 0.95094085 0.53773297]]]


5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

np.nan == np.nan

In [23]:
np.nan == np.nan
#The reason the expression np.nan == np.nan is False may be in that NaN are just substitutes or "place-holders" for missing numerical values. 
#Nonetheless, that does not imply that the original numerical values of different NaN are the same: NaN is just working as a constant. 
#Hence, the expression np.nan == np.nan is False as far as the original numercial values are unknown, 
# so it is not possible to assert they are equivalent


False

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [19]:
#First I calculated the mean for np2 using np.mean and saved it
mean = np.mean(np2)
#Then I rounded the mean to two digits
mean = str(round(mean, 2))

#Second I calculated the standard deviation for np2 using np.mean and saved it
var = np.var(np2)
#Then I rounded the standard deviation to two digits
var = str(round(var, 2))

#Finally I printed the output with f-string
print(f"The mean of np2 is {mean}, and the standard deviation is {var} ")


The mean of np2 is 49.91, and the standard deviation is 18.18 


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels