# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [3]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

In [50]:
#1
even_values = (np1%2==0) #We use the filter to extract the even numbers of the array in an object
np1[even_values] = 100 #We replace those numbers with 100 in the array
print(np1) #We print the array

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

In [56]:
#2
m = np.arange(0, 9) #We create the array with the values raging from 0 to 8
m = m.reshape(3, 3) #We reshape it as a 3x3 matrix
print(m) #We print the new matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [78]:
# 3
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(1,11) #We create the array that goes from 1 to 10
R = sliding_window_view(Z, window_shape=4) #We use the sliding window view function to create the new array
print(R) #We print the new array

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [1]:
# 4
import numpy as np #First we import numphy as np
random = np.random.random((3,3,3)) #Second, we save in an object the array specifying we want a random distribution in 3X3X3
#random.random gives random numbers from 0 to 1
#3X3X3 gives you 3 arrays pf 2 dimensions by 3X3
print(random)#We print our answer

[[[0.89254881 0.43289313 0.15495567]
  [0.39037709 0.70633416 0.38351371]
  [0.47171344 0.93764361 0.07137183]]

 [[0.816229   0.81680014 0.34195998]
  [0.25603203 0.8484631  0.23959137]
  [0.78402343 0.21016488 0.84864378]]

 [[0.03494344 0.38186013 0.05139342]
  [0.60167028 0.45204085 0.3310157 ]
  [0.1526774  0.13112605 0.51319863]]]


In [2]:
#5 
#The expression is false because:
##NaN is short for Not a number. Represents entries that are undefined or missing values in a dataset.
##NaN represents a float-point number wich means that it doesn't satisfies the axioms of arithmetic.
##So, even if we give meanings to NaN, since is define as a float number it cannot respond to the <, >, = sings
## So since it's not a defined number, we can't say i'ts equal, more or less than anyyhing, not even another NaN
import numpy as np
print(np.nan == np.nan)

False


In [6]:
#6
#For using the fstring, we define first the functions 
#np.mean will give us the mean from the array we want
def mean(x):
    return np.mean(x)
#no.var will give us the variance from the array we want
def variance(y):
    return np.var(y)
#We print our F-string aplying the functions to the array np2
f"the mean is {mean(np2)} and the variance is {variance(np2)}."

'the mean is 50.21219381004574 and the variance is 16.459262414381143.'

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels