In [1]:
##Ass3

In [3]:
#Exercise 1: NUMPY

In [2]:
#We get the numpy at the document. We will use them at all six exercises.
import numpy as np

In [4]:
##EXERCISE 1
#We create the asked numpy "np1".
np1 = np.arange( 200, 750)
np1

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38

In [5]:
#Here, we concentrate the values of np1 at "a". Then, we identify all the even numbers using the filter and we create an object called "even_numbers" with them. Finally, we replace them with "100".
a = np.array(np1)
even_numbers = (a%2 == 0)
a[even_numbers] = 100
a

array([100, 201, 100, 203, 100, 205, 100, 207, 100, 209, 100, 211, 100,
       213, 100, 215, 100, 217, 100, 219, 100, 221, 100, 223, 100, 225,
       100, 227, 100, 229, 100, 231, 100, 233, 100, 235, 100, 237, 100,
       239, 100, 241, 100, 243, 100, 245, 100, 247, 100, 249, 100, 251,
       100, 253, 100, 255, 100, 257, 100, 259, 100, 261, 100, 263, 100,
       265, 100, 267, 100, 269, 100, 271, 100, 273, 100, 275, 100, 277,
       100, 279, 100, 281, 100, 283, 100, 285, 100, 287, 100, 289, 100,
       291, 100, 293, 100, 295, 100, 297, 100, 299, 100, 301, 100, 303,
       100, 305, 100, 307, 100, 309, 100, 311, 100, 313, 100, 315, 100,
       317, 100, 319, 100, 321, 100, 323, 100, 325, 100, 327, 100, 329,
       100, 331, 100, 333, 100, 335, 100, 337, 100, 339, 100, 341, 100,
       343, 100, 345, 100, 347, 100, 349, 100, 351, 100, 353, 100, 355,
       100, 357, 100, 359, 100, 361, 100, 363, 100, 365, 100, 367, 100,
       369, 100, 371, 100, 373, 100, 375, 100, 377, 100, 379, 10

In [6]:
##EXERCISE 2
#We create a np.arange from 0 to 8 (as the last number will not get accounted, we put 9)
threexthree = np.arange(0, 9) 
#Now, we divide the np.arange using the function reshape to get the form of a 3x3.
threexthree=threexthree.reshape(3, 3) 
print(threexthree)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
##EXERCISE 3
#The code used works as follow:
#We wish to get a group of four values. So, the first parenthesis goes from 1 to 5. We remember that 5 will then be excluded, because it is the maximum and values just go in a step of 1 by 1).
#After, we get a [None, :]. This, united to the [:, None] at last. Both mark the beginning and end of the array. The ":" show the continuity of the array, as we just need to create an array 1-dimensional.
#Then, it appears a +1. This means that every value of every row of this np.arange will be added by 1, realted to their previous row.
#Also, it is specified the number "7", because to arrive at the [ 7,  8,  9, 10] asked, we need the first arrangement of 4 values repeated 7 times. Another way to interpretate this is that the first value of the first row (1) need to be multiplied by 7 times so it arrives to the number "7" at the beginning of the group.

Z = np.arange(1,5)[None, :] + 1*np.arange(7)[:, None]
Z

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [8]:
#We use the previous code to concatenate the value using "np.concatenate" and we create the object R.

R=np.concatenate(np.arange(1,5)[None, :] + 1*np.arange(7)[:, None])
R

array([ 1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,  5,  6,  7,  5,
        6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10])

In [9]:
##EXERCISE 4

#Here, we create a matrix of three blocks (called "threexthreexthree", each of three lines and every line with three numbers. 
#For this, we use random numbers with the np.random function.
#We print the result.

threexthreexthree = np.random.random((3,3,3)) 
print(threexthreexthree)

[[[0.11414026 0.01263018 0.00535288]
  [0.07070731 0.84896948 0.55039802]
  [0.9804887  0.92523155 0.23255636]]

 [[0.240877   0.19933928 0.041556  ]
  [0.10011276 0.94013272 0.74437989]
  [0.86278762 0.75342519 0.54873338]]

 [[0.77628047 0.74196722 0.30820893]
  [0.45244274 0.31045595 0.17400479]
  [0.94639845 0.33206799 0.59720444]]]


In [10]:
##EXERCISE 5
np.nan == np.nan
#This expression results false because Nan has two meaning at Python. 
#At the beginning of this file, we specified that np was numpy. 
#This means that NAN, in one hand, is a float value, which is a value that is not defined yet, but will get (sooner or later) a number, text, etc. 
#Nevertheless, on the other hand, Nan is "Not a number". Here, it says that the value is unexistant.
#So, in case we affirm that these two values are equal, that would be false. As one value is not defined yet, we can't say it is equal to a value that is already a blanck space. 
#In other words, a value available to fill is not the same to one that is already defined to be empty.

False

In [11]:
##EXERCISE 6
#We create the object np2 with the instructions of the assignement.
np2 = np.random.normal( 50 , 4, 300)
np2

array([53.44196152, 59.7441832 , 46.79590657, 48.19750258, 48.8669081 ,
       49.99541981, 47.75322714, 50.37527837, 50.66799832, 45.71656909,
       42.33258355, 45.65209816, 50.74918233, 54.77722738, 49.22045316,
       57.33332323, 55.38856761, 49.25677853, 47.78648575, 47.05689434,
       55.75553066, 47.23498384, 43.42444977, 51.66798927, 53.43665304,
       50.13284579, 51.10940551, 49.71189366, 46.36257637, 52.30510344,
       52.5967753 , 52.76631871, 50.1039798 , 41.16087588, 61.78004997,
       43.5652241 , 41.57764983, 51.07128918, 45.64850235, 48.1409093 ,
       47.06806106, 54.96056278, 46.79747442, 49.20383416, 50.99808381,
       58.5544553 , 50.18982611, 44.11931188, 49.44912473, 48.9253259 ,
       54.05097149, 51.1480894 , 54.7781548 , 45.26706077, 46.95579481,
       48.85676862, 52.52446957, 59.14657948, 51.81323353, 43.65123359,
       46.29966184, 51.74132489, 46.60613169, 52.04536426, 50.75178843,
       50.87163876, 52.9230479 , 51.45596754, 63.24184504, 52.63

In [12]:
#We get the mean of this array with the function "np.mean"
mean = np.mean(np2)
mean
#We use f-string to release the message with the mean.
F"The mean of np2 is {mean}"

'The mean of np2 is 49.97425533826054'

In [13]:
#We get the standard deviation of this array with the function "np.var"
dev = np.var(np2)
dev
#We use f-string to release the message with the deviation.
F"The standard deviation of np2 is {dev}"

'The standard deviation of np2 is 16.90017245573983'

In [14]:
#Exercise 2: PANDAS

In [3]:
##read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
import pandas as pd

In [2]:
#Debido a que es la primera vez trabajando con una base de datos se nos pide instalar esta extensión de python para poder 
#importar la base de datos
conda install -c conda-forge pyreadstat

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Lenovo\anaconda3

  added / updated specs:
    - pyreadstat


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.12.0               |   py39hcbf5309_0         1.0 MB  conda-forge
    pyreadstat-1.1.7           |   py39h94cc256_0         1.3 MB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.3 MB

The following NEW packages will be INSTALLED:

  pyreadstat         conda-forge/win-64::pyreadstat-1.1.7-py39h94cc



==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda




In [18]:
conda update -n base -c defaults conda

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Lenovo\anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-package-handling-2.0.2|   py39haa95532_0         286 KB
    conda-package-streaming-0.7.0|   py39haa95532_0          27 KB
    pyjwt-2.4.0                |   py39haa95532_0          38 KB
    zstandard-0.18.0           |   py39h2bbff1b_0         310 KB
    ------------------------------------------------------------
                                           Total:         661 KB

The following NEW packages will be INSTALLED:

  conda-package-str~ pkgs/main/win-64::conda-package-streaming-0.7.0-py39haa95532_0
  zstandard          pkgs/main/win-64::zstandard-0.18.0-py39h2bbff1b_0

The following packages will be UPDATED:

  conda-package-han~                   1.7.3-py39h8cc25b3_1 --> 2.0

In [2]:
#Aquí primero importamos la función para poder leer archivos .sav e importamos la base de datos 
import pandas as pd
import savReaderWriter as sav
rec1 = pd.read_spss( fr"REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

labels = metadata[3]

In [3]:
# Aquí revisamos las etiquetas de cada columna, así como la información de cada una
labels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [4]:
#Hacemos una revisión de la base para asegurarnos de que es la correcta
rec1

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
0         1.0  2019.0  1434.0   4.0  ...       No       No       No  010101   
1         1.0  2019.0  1434.0   1.0  ...       No       No       No  010101   
2         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
3         1.0  2019.0  1434.0   3.0  ...       No       No       No  010101   
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No       No  250401   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No       No  250401   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No       No  250401   

        V022      V005          V190      V191  \
0        3.0  154803.0          Rico  1.234450   
1        3.0  154803.0          Rico  1.234450   
2        3.0  154803.0          Rico  1.295611   
3        3.0  154803.0          Rico  1.295611   
4        3.0  154803.0        Pobrer -0.256431   
...      ...       ...           ...       ...   
38330  249.0  244995.0  El más pobre -1.750187   
38331  249.0  244995.0  El más pobre -1.676861   
38332  249.0  459792.0  El más pobre -1.585333   
38333  249.0  459792.0  El más pobre -1.650159   
38334  249.0  244995.0  El más pobre -1.644720   

                                        mujeres12a49  NCONGLOME  
0                    Mujeres de 15 a 49 años de edad     7065.0  
1      Mujeres de 12 a 14 de edad, nunca embarazadas     7065.0  
2                    Mujeres de 15 a 49 años de edad     7065.0  
3                    Mujeres de 15 a 49 años de edad     7065.0  
4                    Mujeres de 15 a 49 años de edad     7065.0  
...                                              ...        ...  
38330                Mujeres de 15 a 49 años de edad    15783.0  
38331                Mujeres de 15 a 49 años de edad    15783.0  
38332                Mujeres de 15 a 49 años de edad    15783.0  
38333                Mujeres de 15 a 49 años de edad    15783.0  
38334                Mujeres de 15 a 49 años de edad    15783.0  

[38335 rows x 105 columns]

In [35]:
##EXERCISE 1
#Revisamos si el identificador "CASEID" es único en la base, es decir, nos aseguramos de que este identifique los casos (las filas)
#de manera única
(rec1['CASEID']).is_unique

True

In [36]:
##EXERCISE 2
#Establecemos mediante el método .set_index a CASEID como el nuevo index, el nuevo índice (la posición de cada registro en el
#conjunto de datos) de nuestra dataframe
rec1.set_index('CASEID')

ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

In [22]:
##EXERCISE 3
#El ejercicio nos pide realizar una filtración de valor, por un lado, de la edad de las encuestadas (15-30) y la zona residencial
#(urbano), si en este caso utilizaramos el método .loc no nos permitiría fitrar un rango de edad con dos condiciones <15 y >30 
#solo perminitía explicitar una de estas condiciones; por ello, usamos el método .query para poder realizar lo antes mencionado

#rec2 = rec1.loc[ (rec1.V012 >15) &  (rec1.V102 == 'Urbano') , : ]
#rec2

rec3= rec1.query("`V012` >= 15 and `V012` <= 30 & `V102`== 'Urbano'")


In [23]:
##Revisamos las primera 30 filas de la columna para asegurarnos de que se realizó la filtración
rec3['V009'].head(n=30)

4      5.0
5     11.0
8      6.0
9      9.0
12     5.0
14     9.0
15     3.0
17     1.0
18    11.0
21     7.0
22    10.0
23     9.0
24     1.0
25     5.0
28    10.0
30    10.0
32     3.0
35     3.0
36     7.0
40     2.0
42     7.0
43     1.0
45     3.0
47     4.0
49    10.0
51    12.0
53     9.0
54     9.0
55     7.0
59     2.0
Name: V009, dtype: float64

In [5]:
##EXERCISE 4
#Primero creamos una copia para no dañar la base principal en nuestro intento
rec4 = rec1.copy()

In [7]:
#Dentro de esta nueva base creamos una nueva columna vacía llamada mes_nac (mes de nacimiento)
rec4['mes_nac'] = rec4['V009'] 
#Para poder reemplazar con valor str los valores numéricos (intg) de la variable mes de nacimiento necesitamos que ambas variables
#sean del mismo tipo, por eso cambiamos el tipo de variable del a str
rec4['mes_nac'] = rec4['mes_nac'].apply(str) 


In [9]:
#Finalmente usamos el método .replace para cambiar los valores de la variable
rec4['mes_nac'] = rec4[ 'mes_nac' ].replace(['1.0', '2.0', '3.0', '4.0',
        '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'],[ 'jan','feb','mar','apr','may','jun','jul','agu','sep','oct','nov','dic'])

In [10]:
rec4['mes_nac'].head(n=30)

0     apr
1     jan
2     jun
3     mar
4     may
5     nov
6     nan
7     nan
8     jun
9     sep
10    agu
11    dic
12    may
13    oct
14    sep
15    mar
16    oct
17    jan
18    nov
19    agu
20    apr
21    jul
22    oct
23    sep
24    jan
25    may
26    sep
27    jul
28    oct
29    apr
Name: mes_nac, dtype: object