# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [4]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

In [8]:
# We created a boolean mask to identify the even numbers (%2==0) in np1. 
#Then, we used indexing to replace only the even numbers with 100.
#We printed np1 with the changes.

even_numbers = (np1%2==0)
np1[even_numbers]=100
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

In [11]:
# We created an array starting at 0 to 8. 
# We reshaped it to a matrix with 3 rows and 3 columns.
#We printed the resulting matrix.

np3= np.arange(0, 9)
np3= np.reshape(np3, (3,3))
print (np3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
# We created the Z array with values ranging from 1 to 10.

Z = np.arange(1, 11)
a=np.arange(1,11)
z= (Z[0:4], Z[1:5],Z[2:6],Z[3:7],Z[3:8],Z[4:9],Z[5:10],Z[6:11])

z1 = (Z[0:4], Z[1:5],Z[2:6],Z[3:7],Z[3:8],Z[4:9],Z[5:10],Z[6:11])
##acabar

In [31]:
z2=np.arange(1,5)
z2

array([1, 2, 3, 4])

In [35]:
R= np.concatenate((Z, a),axis=1)
print (R)


AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
#We created a 3x3x3 array using random values

np4= np.random.random((3,3,3))
print (np4)

[[[0.64959055 0.41733781 0.33676956]
  [0.12827964 0.90363697 0.49607868]
  [0.05646262 0.44439928 0.85643449]]

 [[0.97413359 0.91934932 0.62451275]
  [0.86859466 0.87609932 0.75899113]
  [0.78860295 0.82857275 0.48757368]]

 [[0.99491956 0.91281479 0.51576251]
  [0.67582534 0.03388934 0.24313284]
  [0.00327556 0.98518018 0.84445575]]]


In [10]:
##np.nan is used to creat "Not a number (NaN)", [explanation]
np.nan == np.nan

False

In [27]:
#We printed the mean of np2.
#We calculated the variance of np2 (np.var).
#Then, we calculated the standard deviation by getting the square root of it with np.sqrt.
#We printed the result.

mean_np2= np.round(np.mean(np2))

sd_np2= np.sqrt(np.var(np2))
sd_np2= np.round(sd_np2)


print(f"The mean of np2 is {mean_np2} and the standard deviation is {sd_np2}. ")

The mean of np2 is 50.0 and the standard deviation is 4.0. 


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [1]:
# read REC0111 data
import pandas as pd
!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [2]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [11]:
#With intention 

rec1
my_series = rec1['CASEID'].squeeze()
my_series
print (type(my_series))
print(my_series.is_unique)

<class 'pandas.core.series.Series'>
True


In [ ]:
#We use method set.data to make the CASEID column the index of our data set.

CASEID.set_index(keys, *, drop=True, append=False, inplace=False, verify_integrity=False)


In [ ]:
#We use method .query to keep women who are 15-30 years old and live in Urban areas.

rec1.query(expr, *, inplace=False, **kwargs)


In [ ]:
#We generate a new column with the month of born

# Declare a list that is to be converted into a column
month = ['jan', 'feb', 'mar', 'apr', "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
  
# Using 'Month' as the column name
# and equating it to the list
rec1['Month'] = month
  
# Observe the result
print(rec1)
