# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [7]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

### Solución:

#### 1)




#### 4)

In [16]:
# We create a 3x3x3 array with random values
Qu3=np.random.random((3,3,3))
print(Qu3)


[[[0.75736399 0.21501054 0.67135748]
  [0.41596391 0.71451991 0.46402473]
  [0.40534969 0.83231104 0.3645487 ]]

 [[0.31021096 0.25711174 0.57819382]
  [0.68401302 0.48706548 0.58052907]
  [0.93581813 0.50795929 0.98172399]]

 [[0.02409707 0.74724485 0.91875541]
  [0.70261232 0.83541342 0.03236236]
  [0.85647072 0.2215915  0.83641823]]]


#### 5) 

In [18]:
#The following expression is FALSE. Explain why. 

np.nan == np.nan

False

$ Explanation: $ According to stackoverflow, the IEEE 754 specification for "floating point" numbers states that undefined values ("NaN") will never be equal. This is because that standard defines how exactly a number is stored in memory (that is, what should be returned by operations and what results should be returned by comparisons).

In this sense, "NaN" is used as a kind of placeholder for an undefined state. Therefore, mathematically speaking, an undefined value is not equal to, greater than, or less than another undefined value. Therefore, it is defined by comparison that if one or both of the operands are "NaN", the result of the expression will always be false.

#### 6)

In [28]:
# First, we got the mean of NP2
mean = np.mean(np2)

# Then, we got the standard deviation. We calculated the variance of np2 first and then we get the square root (np.sqrt) in order to get the standard deviation. 
var = np.var(np2)
sdev = np.sqrt(var)

#Finally, we print the result using the f-string we define
print(f"Given np2 data, its mean is {mean} and its standard deviation is {sdev}. Thank you! ")

Given np2 data, its mean is 49.90426406731775 and its standard deviation is 4.021025021678766. Thank you! 


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels