# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [2]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

### Solución:

#### 1)




In [3]:
#Ejercicio 1

## Efectuamos la matriz
np1 = np.arange( 200, 750 )

## Comprobamos que tengamos la matriz de 200 al 750
print(np1)

[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 44

In [4]:
## Indicamos la lista de números pares
even_numbers = (np1%2==0) 

## Indicamos que queremos cambiar cada número par de "np1" con 100
np1[even_numbers]=100

## Comprobamos que cada elemento par de "np1" ha sido reemplazado por 100
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

#### 2)

In [5]:
#Ejercicio 2

##Creamos el "npn" con los valores del 0 al 8
npn = np.arange(0, 9)

## Comporbamos que el array esté del 1 al 8
print(npn)

[0 1 2 3 4 5 6 7 8]


In [6]:
## Usamos la función "np.reshape" para crear la matriz de 3x3
npn= np.reshape(npn, (3,3))

## Comporbamos que tenemos la matriz del 3x3
print (npn)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 3)

In [7]:
#Ejercicio 3

## Creamos un 1D NumPy array con los valores de 1 al 10
Z = np.arange(1, 11)

## Comprobamos que el 1D NumPy array tenga los valores de 1 al 10
print (Z)
type(Z)
print(Z.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [8]:
## Empleamos la función "np.concatenate" para unir distintos fragmentos de "Z"
R = np.concatenate (([Z[0:4]], [Z[2:6]], [Z[3:7]], [Z[4:8]], [Z[5:9]], [Z[6:10]]) , axis = 0)
print(R)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


#### 4)

In [9]:
# We create a 3x3x3 array with random values
Qu3=np.random.random((3,3,3))
print(Qu3)


[[[0.17786085 0.72653294 0.70759354]
  [0.66449357 0.80538    0.54975752]
  [0.27637276 0.1604095  0.91176684]]

 [[0.86593734 0.30266078 0.8111309 ]
  [0.68659182 0.03251303 0.02697981]
  [0.42074215 0.62064222 0.33233922]]

 [[0.01385991 0.33347486 0.28718659]
  [0.48757164 0.11130407 0.94512933]
  [0.92445704 0.55940231 0.89810436]]]


#### 5) 

In [10]:
#The following expression is FALSE. Explain why. 

np.nan == np.nan

False

$ Explanation: $ According to stackoverflow, the IEEE 754 specification for "floating point" numbers states that undefined values ("NaN") will never be equal. This is because that standard defines how exactly a number is stored in memory (that is, what should be returned by operations and what results should be returned by comparisons).

In this sense, "NaN" is used as a kind of placeholder for an undefined state. Therefore, mathematically speaking, an undefined value is not equal to, greater than, or less than another undefined value. Therefore, it is defined by comparison that if one or both of the operands are "NaN", the result of the expression will always be false.

#### 6)

In [11]:
# First, we got the mean of NP2
mean = np.mean(np2)

# Then, we got the standard deviation. We calculated the variance of np2 first and then we get the square root (np.sqrt) in order to get the standard deviation. 
var = np.var(np2)
sdev = np.sqrt(var)

#Finally, we print the result using the f-string we define
print(f"Given np2 data, its mean is {mean} and its standard deviation is {sdev}. Thank you! ")

Given np2 data, its mean is 50.36845984924571 and its standard deviation is 4.053734170900439. Thank you! 


# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [12]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

ModuleNotFoundError: No module named 'savReaderWriter'

In [ ]:
dict_varlabels