# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [72]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [91]:
#We create a filter called even_numbers that returns a boolean. When np1 is even, it returns True
even_numbers = np1%2==0

#We index with the filter and replace the values that achieve the condition with 100
np1[even_numbers] = 100

In [92]:
np1

array([[100],
       [201],
       [100],
       [203],
       [100],
       [205],
       [100],
       [207],
       [100],
       [209],
       [100],
       [211],
       [100],
       [213],
       [100],
       [215],
       [100],
       [217],
       [100],
       [219],
       [100],
       [221],
       [100],
       [223],
       [100],
       [225],
       [100],
       [227],
       [100],
       [229],
       [100],
       [231],
       [100],
       [233],
       [100],
       [235],
       [100],
       [237],
       [100],
       [239],
       [100],
       [241],
       [100],
       [243],
       [100],
       [245],
       [100],
       [247],
       [100],
       [249],
       [100],
       [251],
       [100],
       [253],
       [100],
       [255],
       [100],
       [257],
       [100],
       [259],
       [100],
       [261],
       [100],
       [263],
       [100],
       [265],
       [100],
       [267],
       [100],
       [269],
       [100],
      

2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method.

In [61]:
#We create an array with the values from 0 to 8. 
#Note that the range is exclusive so it is (0,9) in order to include the 8
matrix = np.arange(0,9)

#We reshape it so it becomes a 3x3 matix
matrix=np.reshape(matrix,(3,3))   
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array Z = [1,2,3,4,5,6,7,8,9,10], generate an array R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]?.Hint: Use np.arange and np.concatenate

In [62]:
#We create an array Z with values from 1 to 10
Z = np.arange(1,11)

#We concatenate fractions of Z by indexing Z as suggested by the exercise
R = np.concatenate(([Z[0:4]], [Z[1:5]], [Z[2:6]], [Z[3:7]], [Z[4:8]], [Z[5:9]], [Z[6:10]]), axis=0)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [14]:
#We generate three vectors with the command np.random.random, which
#give you random values. 
np_random = np.random.random((3,3))
np_random


array([[0.39725534, 0.98045478, 0.01737665],
       [0.4414128 , 0.75850407, 0.22890397],
       [0.86046045, 0.57519278, 0.78884178]])

5. Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow.

In [15]:
#nan is not a number and is a commom missing data representation. Nan cannot be equal to itself because nnan is the result of a failure
#The result of one failure cannot be equal to the result of any other failure
#and unknown values cannot be equal to each other.

np.nan==np.nan

False

6. Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

In [23]:
#First, we get the mean and variance with the command np_mean and np_var, rescpectively.
#After that, we use f-string to show the value of the variables as a string.

type(np2)
#f-string 
#np.meam
np_mean= np.mean(np2) 
np_var=np.var(np2)
f"La desviación estándar de np2 es {np_mean}. Y su media es {np_var}"

'La desviación estándar de np2 es 50.13089160509619. Y su media es 16.470711192615507'

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [17]:
# read REC0111 data
import pandas as pd
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss(r"C:\Users\AMD Ryzen\Documents\GitHub\QLAB_Summer_Python\_data\endes\2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader(r"C:\Users\AMD Ryzen\Documents\GitHub\QLAB_Summer_Python\_data\endes\2019/REC0111.sav",
                         ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [18]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [5]:
type(rec1)

pandas.core.frame.DataFrame

### 1

In [6]:
# "rec1" to call our df, "'CASEID'" to specify we want that variable to be evaluated by the function "is_unique"
( rec1[ 'CASEID'] ).is_unique

True

### 2

In [7]:
# "rec1" to call our df, "set_index" to call the method
rec1.set_index('CASEID') # "'CASEID'" to specify we want our index to be named after that variable

ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

### 3 


In [20]:
# we use query to filter the data with mutiple conditions, based on the TRUE values that we put
# in our code. 
# Here I display the variables that we are going to use, for age and area.
rec1[['V012','V025']]

V012    V025
0      33.0  Urbano
1      12.0  Urbano
2      36.0  Urbano
3      49.0  Urbano
4      28.0  Urbano
...     ...     ...
38330  48.0   Rural
38331  31.0   Rural
38332  46.0   Rural
38333  25.0   Rural
38334  23.0   Rural

[38335 rows x 2 columns]

In [36]:
#Now we select the values that we want to be TRUE out of this variables with query.
rec1.query('V012 >= 15 and V012 <= 30 and V025 =="Urbano"')

ID1             HHID              CASEID    V001   V002  V003  \
4      2019.0        000104801        000104801  2     1.0   48.0   2.0   
5      2019.0        000113601        000113601  2     1.0  136.0   2.0   
8      2019.0        000116701        000116701  1     1.0  167.0   1.0   
9      2019.0        000119101        000119101  1     1.0  191.0   1.0   
12     2019.0        000203001        000203001  2     2.0   30.0   2.0   
...       ...              ...                 ...     ...    ...   ...   
38162  2019.0        324202401        324202401  2  3242.0   24.0   2.0   
38163  2019.0        324202501        324202501  3  3242.0   25.0   3.0   
38164  2019.0        324203901        324203901  1  3242.0   39.0   1.0   
38165  2019.0        324204501        324204501  2  3242.0   45.0   2.0   
38170  2019.0        324206901        324206901  3  3242.0   69.0   3.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
5         1.0  2019.0  1434.0  11.0  ...       No       No       No  010101   
8         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
9         1.0  2019.0  1434.0   9.0  ...       No       No       No  010101   
12        2.0  2019.0  1432.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38162  3242.0  2019.0  1436.0   2.0  ...       No       No       No  250302   
38163  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38164  3242.0  2019.0  1436.0   8.0  ...       No       No       No  250302   
38165  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38170  3242.0  2019.0  1436.0  10.0  ...       No       No       No  250302   

        V022      V005          V190      V191  \
4        3.0  154803.0        Pobrer -0.256431   
5        3.0  154803.0      Más rico  1.435294   
8        3.0  154803.0      Más rico  1.672440   
9        3.0  154803.0        Pobrer  0.234148   
12       2.0   65298.0        Pobrer -0.196449   
...      ...       ...           ...       ...   
38162  248.0  203603.0        Pobrer -0.463931   
38163  248.0  567613.0        Pobrer -0.576118   
38164  248.0  567613.0  El más pobre -0.940013   
38165  248.0  203603.0  El más pobre -0.656011   
38170  248.0  567613.0        Pobrer -0.574662   

                          mujeres12a49  NCONGLOME  
4      Mujeres de 15 a 49 años de edad     7065.0  
5      Mujeres de 15 a 49 años de edad     7065.0  
8      Mujeres de 15 a 49 años de edad     7065.0  
9      Mujeres de 15 a 49 años de edad     7065.0  
12     Mujeres de 15 a 49 años de edad     7068.0  
...                                ...        ...  
38162  Mujeres de 15 a 49 años de edad    45556.0  
38163  Mujeres de 15 a 49 años de edad    45556.0  
38164  Mujeres de 15 a 49 años de edad    45556.0  
38165  Mujeres de 15 a 49 años de edad    45556.0  
38170  Mujeres de 15 a 49 años de edad    45556.0  

[12236 rows x 105 columns]

### 4

In [66]:
# The column that we are going to use is V009, which has the month of born but in numbers.
rec1[['V009']]

V009
0       4.0
1       1.0
2       6.0
3       3.0
4       5.0
...     ...
38330  12.0
38331   6.0
38332   7.0
38333  12.0
38334  10.0

[38335 rows x 1 columns]

In [63]:
#First we create a new column with the values of V009. And then, we convert the numbers to strings
#just to make it easier to replace the months of birth.
rec1[ 'Month' ] = rec1[ 'V009' ]
rec1['Month'] = rec1['Month'].apply(str)

In [64]:
#Now we use "replace" to change the values in our new column.
rec1[ 'Month' ] = rec1[ 'Month' ].replace(['1.0', '2.0', '3.0', '4.0', 
        '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'],[ 'JAN', 'FEB', 
        'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'])

In [65]:
rec1[['Month']]

Month
0       APR
1       JAN
2       JUN
3       MAR
4       MAY
...     ...
38330   DEC
38331   JUN
38332   JUL
38333   DEC
38334   OCT

[38335 rows x 1 columns]